import { useEffect, useState } from 'react';
import { FileText, Printer, Download, Sparkles } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { useApi } from '../hooks/useApi';
import { useAnalysisScope } from '../hooks/useAnalysisScope';
import { api } from '../lib/api';
import { formatMetric } from '../lib/format';
import { PageHeader } from '../components/PageHeader';
import { EmptyState, LoadingState } from '../components/Status';
interface SavedScenario{id:string;created_at:string;inputs:Record<string,number|string|null>;result:Record<string,any>}
interface Report{id:string;title:string;year:number;grid_id:string;created_at:string;evidence_hash:string;sector:{name:string};summary:{mode:string;model:string|null;paragraphs:string[];validation:string;reason?:string};sources:Array<Record<string,any>>;scenarios:SavedScenario[];facts:Array<{id:string;text:string}>;coverage:Record<string,number>;scope:string}
export function ReportsPage(){
 const {year,gridId}=useAnalysisScope();const scope=useApi<{selected_sector:{grid_id:string}}>(`/dashboard?year=${year}`);const [params]=useSearchParams();
 const scenarios=useApi<SavedScenario[]>('/scenarios');const saved=useApi<Array<{id:string;year:number;created_at:string;grid_id:string}>>('/reports');
 const engine=useApi<{status:string;model:string|null}>('/reports/engine');
 const [chosen,setChosen]=useState<string[]>([]);const [useLocal,setUseLocal]=useState(false);const [report,setReport]=useState<Report|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{setChosen(params.get('scenario')?[params.get('scenario')!]:[]);setReport(null);setError(null);},[year,gridId,params]);
 const rows=Array.isArray(scenarios.data)?scenarios.data.filter(s=>s.inputs.type!=='OPTIMIZATION'&&Number(s.inputs.year??2025)===year&&(s.inputs.grid_id===(gridId||scope.data?.selected_sector?.grid_id))):[];
 const generate=async()=>{setBusy(true);setError(null);try{const r=await api<Report>('/reports',{method:'POST',body:JSON.stringify({year,grid_id:gridId,scenario_ids:chosen,use_local_model:useLocal})});setReport(r);void saved.reload();}catch(e){setError(e instanceof Error?e.message:'보고서 작성 실패');}finally{setBusy(false);}};
 const open=async(id:string)=>{setBusy(true);setError(null);try{setReport(await api<Report>(`/reports/${id}`));}catch(e){setError(e instanceof Error?e.message:'조회 실패');}finally{setBusy(false);}};
 return <div className="page reports-page"><div className="no-print"><PageHeader eyebrow="EVIDENCE REPORT" title="도시계획 검토 보고서" description="저장된 시나리오와 출처를 고정하여 다시 확인할 수 있는 한국어 보고서를 작성합니다."/>
 <section className="panel report-builder"><div className="panel-title"><div><span>COMPARABLE SCENARIOS</span><h3>비교할 계획안 선택</h3></div><span className="badge">최대 3개 · 같은 연도와 격자</span></div><p>시뮬레이션에서 계산한 계획안을 선택하세요. 계획안 없이 현재 자료 현황만 보고서로 작성할 수도 있습니다.</p>
 {scenarios.loading?<LoadingState/>:rows.length?<div className="scenario-picker">{rows.map((s,i)=><label key={s.id}><input type="checkbox" checked={chosen.includes(s.id)} disabled={!chosen.includes(s.id)&&chosen.length>=3} onChange={e=>setChosen(e.target.checked?[...chosen,s.id]:chosen.filter(id=>id!==s.id))}/><span><strong>{s.inputs.floors}층 · {s.inputs.building_count}동</strong><small>{String(s.inputs.grid_id??'기본 격자')} · {new Date(s.created_at).toLocaleString('ko-KR')}</small></span><b>{formatMetric(s.result?.far,'% ',1)}</b></label>)}</div>:<EmptyState title="이 범위에 저장된 계획안이 없습니다" description="시뮬레이션에서 계획안을 먼저 계산하거나 현재 자료 보고서를 작성하세요."/>}
 {scenarios.error&&<p role="alert" className="inline-error">{scenarios.error}</p>}<div className="report-actions"><label className="ai-option"><input type="checkbox" checked={useLocal} disabled={engine.data?.status!=='READY'||busy} onChange={e=>setUseLocal(e.target.checked)}/><Sparkles size={16}/>로컬 AI로 핵심 근거 선정<small>{engine.data?.status==='READY'?engine.data.model:'로컬 모델 준비 전 · 기본 서식 사용 가능'}</small></label><button className="button primary" disabled={busy} onClick={()=>void generate()}><FileText size={16}/>{busy?'보고서 처리 중…':'보고서 작성'}</button></div><p className="muted">수치는 계산 엔진에서 가져옵니다. AI는 검증된 근거 문장만 선택하며 원본 수치를 다시 계산하지 않습니다.</p></section>
 {error&&<p role="alert" className="inline-error">{error}</p>}
 {saved.data?.length?<section className="report-history"><label>작성 이력<select aria-label="저장 보고서" value={report?.id??''} onChange={e=>e.target.value&&void open(e.target.value)}><option value="">보고서 선택</option>{saved.data.map(r=><option key={r.id} value={r.id}>{r.year}년 · {r.grid_id} · {new Date(r.created_at).toLocaleString('ko-KR')}</option>)}</select></label></section>:null}</div>
 {report&&<><div className="report-export no-print"><span className="badge good">{report.summary.mode==='LOCAL_SLM'?'로컬 AI 근거 요약':'검증된 서식 보고서'}</span><a className="button secondary" href={`/api/reports/${report.id}/markdown`}><Download size={15}/>문서 내려받기</a><button className="button primary" onClick={()=>window.print()}><Printer size={15}/>인쇄 · PDF 저장</button></div><article className="report-paper"><div className="report-kicker">CARBON URBAN DSS · 의사결정 검토자료</div><h1>{report.title}</h1><p className="report-subtitle">{report.sector?.name} · {report.year}년</p><dl className="report-meta"><div><dt>분석 격자</dt><dd>{report.grid_id}</dd></div><div><dt>작성일</dt><dd>{new Date(report.created_at).toLocaleString('ko-KR')}</dd></div><div><dt>작성 방식</dt><dd>{report.summary.validation}</dd></div></dl>
 <h2>검토 요약</h2>{report.summary.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{report.summary.reason&&<p className="muted">{report.summary.reason}</p>}
 <h2>기준 자료와 해석 범위</h2><p>전력 {report.coverage.electricity_months}/12개월 · 가스 {report.coverage.gas_months}/12개월</p><p>{report.scope}</p><p>부분 관측 합계를 완전한 연간 값으로 해석하지 않습니다. 결측 자료는 0으로 대체하지 않습니다. 운영 단계의 1차 추정이며 법적 적합성이나 사업 전체 넷제로 달성을 판정하지 않습니다.</p>
 {report.scenarios.length>0&&<><h2>계획안 비교</h2><div className="table-wrap"><table><thead><tr><th>항목</th>{report.scenarios.map((s,i)=><th key={s.id}>대안 {i+1}</th>)}</tr></thead><tbody>{[['floors','층수','층'],['building_count','동수','동'],['gross_floor_area','연면적','m²'],['far','용적률','%'],['bcr','건폐율','%'],['households','세대수','세대'],['population','계획 인구','명']].map(([key,label,unit])=><tr key={key}><th>{label}</th>{report.scenarios.map(s=><td key={s.id}>{formatMetric(Number(s.result[key]??s.inputs[key]),unit,1)}</td>)}</tr>)}<tr><th>계획 연간 탄소</th>{report.scenarios.map(s=><td key={s.id}>{formatMetric(s.result.annual?.scenario?.carbon_kg,'kgCO₂eq',1)}</td>)}</tr></tbody></table></div><p>계획안은 동일 격자·연도에서 비교하며, 개발부지와 수용 인구가 다르면 동등한 서비스 규모가 아닙니다.</p></>}
 <h2>데이터 출처</h2><div className="table-wrap"><table><thead><tr><th>자료</th><th>기간과 수집일</th><th>확보 현황</th></tr></thead><tbody>{report.sources.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.source_type}</small></td><td>{s.reference_period}<small>{s.collected_at?new Date(s.collected_at).toLocaleDateString('ko-KR'):'미수집'}</small></td><td>{s.normalized_row_count}행<small>{s.status}</small></td></tr>)}</tbody></table></div><h2>재현 정보</h2><p className="hash-line">보고서 ID {report.id}<br/>근거 SHA256 {report.evidence_hash}</p><p className="muted">생성 당시의 계산 결과와 출처를 보존한 보고서입니다. 이후 데이터 수집이나 설정 변경은 저장된 보고서를 변경하지 않습니다.</p></article></>}
 </div>;
}
