const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const base=process.env.DSS_URL||'http://127.0.0.1:5173';const out=path.resolve('data/validation/refined');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:1100}});const page=await context.newPage();const errors=[];const checks=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base);await page.locator('.metric-card').first().waitFor();assert.equal(await page.locator('.metric-card').count(),8);checks.push('dashboard_eight_metrics');
 await page.getByLabel('분석연도',{exact:true}).selectOption('2022');await page.getByText('이 연도의 기상 자료가 없습니다.').waitFor();checks.push('year_switch_missing_weather');
 await page.getByLabel('분석연도',{exact:true}).selectOption('2025');await page.getByRole('img',{name:'월평균 기온 차트'}).waitFor();await page.screenshot({path:path.join(out,'dashboard.png'),fullPage:true});
 await page.goto(base+'/map');await page.waitForFunction(()=>Number(document.querySelector('.map-canvas')?.dataset.renderedFeatures)>0);await page.getByRole('button',{name:'선택 격자로 확대'}).click();await page.locator('.maplibregl-canvas').click({position:{x:430,y:280}});await page.getByRole('link',{name:'이 격자 시뮬레이션'}).waitFor();await page.screenshot({path:path.join(out,'map.png'),fullPage:true});checks.push('map_render_and_selection');
 await page.getByRole('link',{name:'이 격자 시뮬레이션'}).click();await page.getByRole('button',{name:'30층',exact:true}).click();const [response]=await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/scenarios')&&r.request().method()==='POST'),page.getByRole('button',{name:'시나리오 계산',exact:true}).click()]);assert.equal(response.status(),200);const scenario=await response.json();await page.getByRole('link',{name:'이 계획안으로 보고서 작성'}).waitFor();await page.screenshot({path:path.join(out,'simulation.png'),fullPage:true});checks.push('scenario_calculation_and_report_link');
 await page.getByRole('link',{name:'이 계획안으로 보고서 작성'}).click();await page.getByRole('button',{name:'보고서 작성',exact:true}).click();await page.locator('.report-paper').waitFor();assert.equal(await page.locator('.report-paper').getByText('대안 1',{exact:true}).count(),1);await page.screenshot({path:path.join(out,'report.png'),fullPage:true});checks.push('report_same_scope_comparison');
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'문서 내려받기'}).click()]);await download.saveAs(path.join(out,'report.md'));assert(fs.readFileSync(path.join(out,'report.md'),'utf8').includes('근거 SHA256'));checks.push('report_markdown_download');
 await page.emulateMedia({media:'print'});await page.screenshot({path:path.join(out,'report-print.png'),fullPage:true});assert.equal(await page.locator('.sidebar').isVisible(),false);await page.emulateMedia({media:'screen'});checks.push('print_layout');
 await page.setViewportSize({width:390,height:844});for(const route of ['/','/map','/simulation','/reports','/data']){await page.goto(base+route);await page.locator('.page-header').waitFor();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);assert.equal(overflow,false,'mobile overflow '+route);await page.screenshot({path:path.join(out,'mobile'+(route.replaceAll('/','_')||'_')+'.png'),fullPage:true});}checks.push('five_mobile_routes_no_horizontal_overflow');
 await page.route('**/api/dashboard?*',r=>r.fulfill({status:503,body:'unavailable'}));await page.goto(base);await page.getByText('데이터를 불러오지 못했습니다').waitFor();checks.push('server_error_is_visible');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({checks,pageErrors:errors},null,2));console.log(JSON.stringify({passed:checks.length,pageErrors:errors}));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
